name: qutanga_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.4.0
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.15
  sqlite3: ^2.1.0  # Add this explicit dependency
  path_provider: ^2.1.1
  path: ^1.9.0
  intl: ^0.18.1
  pie_chart: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.14.0
  build_runner: ^2.4.6
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
